collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5021276
  brandStrength: 0.4297872
  rhythmicContrast: 0.5062497
  brandColors:
    - '#F5D29B'
    - '#11110F'
    - '#433A33'
    - '#73674F'
    - '#D4AA80'
  lightness: 0.5297872
typography_spectrum: 0.4106383
layout_spectrum: 0.2829787
name: Claire and Blair
